name = "ffilesystem"
description = "Lightweight filesystem and path manipulations"
categories = "io"
version = "6.2.0"

[build]
auto-examples = false
auto-tests = false

[install]
library = true

[library]
include-dir = ["include"]
